### ISSUE TITLE
Do you plan to support the Konva.Animation?

### ISSUE THREAD

**Issue by bokuweb** [lavrton/react-konva#1]
Do you plan to support the Konva.Animation?
If want to move rect,  have to use the raf?

**Comment by lavrton** [comment]
How do you want to move rect in terms of React, and JSX?  Animate from one position to another?

**Comment by bokuweb** [comment]
Yes.I want to create game with react-konva.
like this. https://github.com/bokuweb/bmsjs-ithildin/tree/try_react-konva

**Comment by lavrton** [comment]
I added animation note into README.
