### ISSUE TITLE
Event handler that opens up native canvas element

### ISSUE THREAD

**Issue by CharlieGreenman** [lavrton/react-konva#10]
Terrific framework. I am currently trying to get mouse position of mouse onClick(offsetX/offsetY), and the classic e = e || window.event;, is returning the parameters for the element itself.

event: {"evt":{"isTrusted":true},"target":"{\"attrs\":{\"width\":400,\"height\":400},\"className\":\"Rect\"}","currentTarget":"{\"attrs\":{\"width\":400,\"height\":400},\"className\":\"Rect\"}","type":"click"}

**Comment by lavrton** [comment]
Hi. What exactly is your issue about?

**Comment by CharlieGreenman** [comment]
I am trying to get the mouse position of mouse onClick relative to canvas element. Once again, my boundless thanks :)

**Comment by lavrton** [comment]
You can get native click event from `e.evt` object and then calculate a local position (you can get canvas element and screen position from the event). Or you can use `getPointerPosition()`  of `Konva.Stage` instance:
```javascript
handleClick(e) {
        console.log('native event', e.evt);
        console.log('Konva.Circle instance', e.target);
        console.log('mouse position on canvas', e.target.getStage().getPointerPosition());
}
```
Demo: http://jsbin.com/niyego/2/edit?js,output
