### ISSUE TITLE
relative width for stage?

### ISSUE THREAD

**Issue by david8zhang** [lavrton/react-konva#104]
Is it possible to define the stage width to be a percentage (like 100%) instead of an absolute pixel value?

**Comment by lavrton** [comment]
I don't know any ways to do this.
To resolve the issue I am using a width of the parent DOM node for a stage width and then refreshing it on window resize event.

**Comment by mdmusaib** [comment]
can we give stage width to auto, and height to auto is it possible

**Comment by lavrton** [comment]
No. We have to set numbers in pixels. If you want to adjust the size, just recalculate the size of the parent container on its resize. And use that size for Konva stage. For demo take a look here: https://konvajs.org/docs/sandbox/Responsive_Canvas.html#Do-you-need-responsive-adaptive-canvas-for-you-desktop-and-mobile-applications
