### ISSUE TITLE
Coloring of Rect

### ISSUE THREAD

**Issue by AleksandarSavic95** [lavrton/react-konva#105]
Hi there.
First of all, thank You for react-konva! It has helped me alot, and it is, well.. mostly simple to use.

The problem I am facing is:
I have a <Table> component wihich contains:

    <Group> <Rect /> <Text /> </Group>
In the parent component called <Table**s**/>, I iterate throguh an array of attributes for each \<Table\> and I render all the \<Table\> components.
**The problem:** \<Text/\> component gets the fill property which is a string with a color (like 'blue'), and the \<Rect /\> doesn't. My code is below:

    <Group draggable={true}
         x={this.props.x} y={this.props.y}
         ref={this.props.id} // this is unique - from DataBase
         onDragEnd={()=>this.handleDragEnd(this.props.id)}
         onClick={()=>this.props.tableClick({id: this.props.id})} //, x: this.props.x, y: this.props.y
      onMouseEnter={this.props.cursorPointer}
      onMouseLeave={this.props.cursorDefault}>
    <Rect
      ref={`R-${this.props.id}`} // I know it doesn't affect anything but..
      x={this.props.x} y={this.props.y}
      fill={this.props.color} // this doesn't work   <-----------------------------------------***
      width={this.props.width} height={this.props.height}
      stroke={'black'} strokeWidth={2}
    />
    <Text
      text={`${this.props.chairCount}`} fill={this.props.color} // this works.. *How?* <----***
      fontSize={30}
      padding={25}
    />
  </Group>

Please answer as soon as possible, since time is really of the essence, and I've already lost a day on this issue.
Thank You for Your time

Greetings,
Aleksandar

**Comment by lavrton** [comment]
Probably because you set `x` and `y` to the `Rect`, so absolute position of the `Rect` is {`2 * x`, `2 * y`} (position of group plus position of the `Rect`). So you don't see it.

This demo works fine: http://jsbin.com/norasuvedu/1/edit?js,output

**Comment by AleksandarSavic95** [comment]
Thank You for a fast response, but it is not working.
I've set a cursor change to a pointing hand (👆) on mouse enter and back to normal on mouse leave.
Interesting thing is that when I enter the Rect with my cursor, it changes to a 👆, so I know the rect is on the good position.
Also, when I draw new tables, they are normally visible, but I can't tell why.
I am writing messages about the colors to the console window, and the color matches (see the image below).
What else can I try?

![image](https://user-images.githubusercontent.com/12213798/27274022-e9dc8f54-54d1-11e7-827e-87142fe96430.png)

**Comment by AleksandarSavic95** [comment]
I've just realized that I was setting the width to a undefined value, and the new tables had the width defined automatically. Sorry for bothering. It is just a dumb mistake.
Thank You for Your time.
I would also like to get a small sample of the contentClick event (found on [Konvajs docs](https://konvajs.github.io/docs/events/Stage_Events.html)).
Thanks once again!
