### ISSUE TITLE
Animation of straight line vs Sloped line (diagonal line)

### ISSUE THREAD

**Issue by thatbeardo** [lavrton/react-konva#107]
To begin with, I really appreciate your efforts for this library and it makes things really simple and smooth. I have a small concern though. When I try to render/animate a straight line let's say the initial state of the line is 
[20, 20, 400, 20] 
to 
[20 , 20, 400, 20, **600, 20**]
things work fine. I see the line being drawn incrementally. This is exactly what I expect when rendering a sloped line ( a diagonal per se)

Consider the similar example. When rendering a sloped line for example: 
[20, 20, 400, 20 ]
to 
[20, 20, 400, 20, **20, 30**]
It does not appear to be a line being drawn from a point 'A' to point 'B'. Instead the diagonal suddenly appears out of nowhere. Here is the code: 

Problematic Case:
```
import React, { Component } from 'react';
import { Layer, Line, Stage } from 'react-konva';

class App extends Component {

    constructor(...args){
        super(...args);
        this.state={color:"green", points: [20, 20, 400, 20]};
    }

    animate() {
     
        var points = this.state.points;
        points = points.concat([20, 30])
       
        this.refs.line.to({points, duration: 0.9});
        this.setState({points: points});
    }

    render() {
    return (
      <div>
          <Stage width={700} height={800}>
              <Layer><Line
                  ref = "line"
                  x={40} y={40} width={this.state.width} height={this.state.height}
                  stroke={this.state.color}
                  points={this.state.points}

                  onMouseLeave = {() => this.animate()}
              /></Layer>
          </Stage>
      </div>
    );
  }
}

export default App;

```

Good Case: 

```
import React, { Component } from 'react';
import { Layer, Line, Stage } from 'react-konva';

class App extends Component {

    constructor(...args){
        super(...args);
        this.state={color:"green", points: [20, 20, 400, 20]};
    }

    animate() {
     
        var points = this.state.points;
        points = points.concat([600, 20])
       
        this.refs.line.to({points, duration: 0.9});
        this.setState({points: points});
    }

    render() {
    return (
      <div>
          <Stage width={700} height={800}>
              <Layer><Line
                  ref = "line"
                  x={40} y={40} width={this.state.width} height={this.state.height}
                  stroke={this.state.color}
                  points={this.state.points}

                  onMouseLeave = {() => this.animate()}
              /></Layer>
          </Stage>
      </div>
    );
  }
}

export default App;

```

**Comment by lavrton** [comment]
As I remember Konva don't really support tweening of arrays with different length.
Probably it may work in some rare cases.

Try to emulate the same length. Like instead of
[20, 20, 400, 20] to [20 , 20, 400, 20, 600, 20]
Try:
[20, 20, 400, 20, 400, 20] to [20 , 20, 400, 20, 600, 20]

**Comment by thatbeardo** [comment]
Well, I reiterate. The line seems to be working fine when we increment it in either the x-direction or the y-direction. However when we render a slant line ( one with some slope ), the animation does not looks like a line being drawn. Instead the line simply pops up and then there is some redundant animation

**Comment by lavrton** [comment]
As I mentioned it is hard to animated array with different length.
Do you expect this result http://jsbin.com/vomuvujoxi/1/edit?js,output? 
```js
    constructor(...args){
        super(...args);
        this.state={color:"green", points: [20, 20, 400, 20, 400, 20]};
    }

    animate() {
        var points = this.state.points.concat();
        points[4] = 20;
        points[5] = 30;
       
        this.refs.line.to({points, duration: 0.9});
    }
```

**Comment by thatbeardo** [comment]
YES YES YES YES YES!!!!!!! This is exactly what I need!!!!!
