### ISSUE TITLE
How to fill a rect with an background image

### ISSUE THREAD

**Issue by janus-reith** [lavrton/react-konva#111]
Or is there a similar approach using an image?
I need to crop out a part of an image and repeat it to fill the container size.

I Could use an Image like described in the readme, but am unable to use it as a Fill pattern

**Comment by lavrton** [comment]
You can use `fillPatternImage`.
Docs: https://konvajs.github.io/docs/styling/Fill.html
Demo: http://jsbin.com/yazofokeyu/1/edit?js,output

**Comment by janus-reith** [comment]
Sorry, found out myself. Is There a way to just cut out an Area of my image and use that as a fill pattern?

ATM i just make the rect 10px and change the filloffset, and repeat its rendering e.g. 60 times to have the expected output - But I consider that really inefficient. Instead I would like to crop the Image to 10px and offset it, then use that as fill.

**Comment by lavrton** [comment]
@janus-reith you can always draw image into off-screen canvas as you want (crop it, rotate, etc). And then use that canvas for `fillPatternImage`

**Comment by janus-reith** [comment]
Great that this is possible, could you give me an example?

**Comment by lionicex** [comment]
Hello!
I want to put an image inside the transformer to resize it but when using fillPatternImage the image is repeated many times. Then I put a filPatternRepeat = "no-repeat" but the image does not fit the Rect box. Can anybody help me?

**Comment by lavrton** [comment]
@lionicex try to use `fillPatternScaleX` and `fillPatternScaleX` to scale the image into required size.

**Comment by lionicex** [comment]
> @lionicex try to use `fillPatternScaleX` and `fillPatternScaleX` to scale the image into required size.

I need adjust the size of the image to the container to be able to resize it. See what happens now every time I enlarge the image in the photos above.

**Comment by lavrton** [comment]
@lionicex I think it is better to use StackOverflow for such questions.

**Comment by imnithi22** [comment]
@lavrton , is there a way to repeat a single image to fill the rect?

**Comment by lavrton** [comment]
`fillPatternImage`
