### ISSUE TITLE
React 15.6 

### ISSUE THREAD

**Issue by damienleroux** [lavrton/react-konva#114]
Hello,

I'm using React  15.6. But react-konva is limited to 15.5 as peer and return a warn when installing it.

Is there any issue when using 15.6? Otherwise we could update package.json react/react-dom peer version.

Thank you

**Comment by lavrton** [comment]
Hi. There are no issues. They work just fine. I will update `package.json`

**Comment by damienleroux** [comment]
thank you

**Comment by lavrton** [comment]
Done
