### ISSUE TITLE
Managing X/Y position in draggable nodes through DragBoundFunc and react state

### ISSUE THREAD

**Issue by RussGlover** [lavrton/react-konva#115]
Is there a good way to go about this? It seems that x/y position is managed primarily in the internal Konva code. I'd kind of like to move towards managing the X/Y positions through react state however. Are there any issues that may arise from this? 

I was planning to call setState in my custom dragBoundFunc, replacing the return statement. At [_setDragPosition](https://konvajs.github.io/api/konva.js.html#line12418) it looks like the internal code could be modified to just call the dragBoundFunc and ignore the return values.  Would this cause any other issues? I will continue my own testing but would be interested in some other opinions.

**Comment by lavrton** [comment]
@RussGlover please give more info about your use case? What do you want to achieve?

**Comment by RussGlover** [comment]
I figured out what was going wrong. All good!
