### ISSUE TITLE
Free Drawing example

### ISSUE THREAD

**Issue by techniq** [lavrton/react-konva#118]
I've been attempting to port Konva's [Free Drawing Demo](https://konvajs.github.io/docs/sandbox/Free_Drawing.html) to use React Konva but I've been struggling to see any lines drawn.  I don't know if I need some explicit `draw()` call or how I'm handling the `React.Image`'s canvas is incorrect...

My WIP is available on codesandbox [here](https://codesandbox.io/s/1w68QYp13).  Any help on how to get this to work would be greatly appreciated.  Thanks.

**Comment by lavrton** [comment]
Yeah. In this case, you will need explicitly `draw()` call. Because react-konva doesn't know that canvas content is changed (so it doesn't call `draw` automatically).
```
this.image.getLayer().draw();
```
https://codesandbox.io/s/wml6yXZ2z

**Comment by techniq** [comment]
@lavrton that was what I was missing, thanks :)

**Comment by 6LACK-N1NJA** [comment]
thanks guys! this tread was really helpful.
