### ISSUE TITLE
No wiki

### ISSUE THREAD

**Issue by drawpen** [lavrton/react-konva#123]
I like this lib, but I can't see any documentation about all components. So for now I have to guess how to create, say a Blob :(

**Comment by lavrton** [comment]
`react-konva` is just a bridge between `React` and `Konva`. So you actually don't need to learn `react-konva`. All documentation about Konva is available here: https://konvajs.github.io/

Blob example: https://konvajs.github.io/docs/shapes/Line_-_Blob.html

Personally, I don't like wiki format. I think documentation in `README.md` or separate site are better options.

I am happy to apply Pull Requests for documentation. For me, it is clear how to find documentation about a Blob and how to apply it to `react-konva`. If you stuck, please, let me know where, and why you weren't able to find the answer so we can update documentation
