### ISSUE TITLE
Gradient on stroke

### ISSUE THREAD

**Issue by Tomisiak** [lavrton/react-konva#125]
Is there any React/Konva way to put gradient on stroke? I was able to do this by getting reference of canvas element and using HTML5 canvas method `createLinearGradient` to get `gradient` object and then pass it as `stroke` prop to `Rect` component. The problem is, it doesn't work on page load when gradient width and height is taken dynamically from some DOM element (`button` in my case). My goal is to create gradient border with radius.

**Comment by lavrton** [comment]
@Tomisiak please provide an example or demo.
You can do all width/height calculations in `componentDidMount()`
