### ISSUE TITLE
Bezier Lines

### ISSUE THREAD

**Issue by ygorlf** [lavrton/react-konva#127]
I noticed that recently was an update on konva that supports bezier parameter on line shape, that is already possible on react-konva?

**Comment by lavrton** [comment]
Yes. Just update `konva` dependency.

**Comment by floric** [comment]
Did this really solve it? Somehow, Line doesn't have the "bezier" property and I'm using konva@2.0.3 and react-konva@1.7.2.

**Comment by lavrton** [comment]
@floric this works just fine:

```
 <Line
  stroke="black"
  points={[50, 50, 200, 50, 200, 200, 50, 200]}
  bezier
/>
```

https://codesandbox.io/s/30914q4rk5

**Comment by floric** [comment]
@lavrton yes, Anton. I tried this later myself. The was/is that I'm using Typescript and the konva typings for Line are missing the property. I will make sure if I'm right and submit a PR to konva in case. Thanks :)

**Comment by gal1419** [comment]
@floric did you solve it?
