### ISSUE TITLE
Konva Text Position

### ISSUE THREAD

**Issue by dcilibiu** [lavrton/react-konva#130]
Hi, I am currently trying to position a dynamic text.
Konva is doing some internal things with it, like multi-line. 
In order to position the text I need to get the height of the text but that is calculated after it renders first time and somehow I need to find a way to force re-rendering. Has anyone experienced this?

**Comment by lavrton** [comment]
@dcilibiu it is not a special issue to `react-konva`. You may have the same use case with usual DOM.
Just read text height on `componentDidMount()` and do re-render as you need.

**Comment by dcilibiu** [comment]
Thanks for the fast response. What you said, reading the height on componentDidMount, I am already doing it, but along the way I need to update the text which changes the height, this case is a bit confusing to me how to manage the position again. It goes as it should only when clicking or doing other stuff (that forces an update),

**Comment by lavrton** [comment]
You can also recheck your layout in `componentDidUpdate`

**Comment by dcilibiu** [comment]
Yes, thank you! I forgot about this one. I managed to manipulate the position after some tweaks.
