### ISSUE TITLE
Typescript error saying onMouseOver does not exist on Circle

### ISSUE THREAD

**Issue by thunderkid** [lavrton/react-konva#131]
In React-konva 1.1.4 compiled with Typescript 2.5.2 (and 2.4), I'm getting incorrect compilation errors. The following:

`<Circle x={50} y={50} radius={10} fill='#ddd' onMouseOver = {(e) => {console.log('yippeee'); }}/>`

gives compilation error:

`Property 'onMouseOver' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Circle> & Readonly<{ children?: ReactNode; }> & Re...'.`

But the code actually works - ie the console log correctly appears on mousing over. Same error appears for `onDrag` etc.

**Comment by lavrton** [comment]
Looks like our Typescript definitions are missing all events.
I will be happy to accept Pull Request.
