### ISSUE TITLE
Dragging a Group element makes the shape 'jump' after dragging

### ISSUE THREAD

**Issue by kevgathuku** [lavrton/react-konva#133]
Hello @lavrton 

I am trying to drag a group of shapes  and when I try to drag them, after the drag is done, the shape `moves` / `jumps` after dragging. Any ideas on how to resolve this? It seems accessing the `x` and `y` values from the shape gives me the wrong values after dragging

Here's a demo of the bug: https://codepen.io/kevgathuku/pen/JrdBMq
I've also set up a repo with the same code here https://github.com/kevgathuku/konva-drag-bug
Try dragging the red square to see the issue
Thanks in advance 😄 

Update:
This only happens if the events are attached to the `Group`. If I attach the events to the `Rect`, everything seems to be working just fine

**Comment by lavrton** [comment]
You have draggable Group. By default it has x = 0, y = 0. When you are dragging the group its position is changing. On `dragend` it will have position, for example, x = 50, y = 50.
The absolute position of rect is changed as well.
In `onDragEnd` you are setting new position for Rect, but old position of group (x=50, y=50) is still there. So a difference of object moving during drag is applied twice, so you see the jump.
Fixed version: https://codepen.io/lavrton/pen/YrXgQz

**Comment by kevgathuku** [comment]
Thanks for the suggestion. I appreciate the quick response.
However, it only seems to be working when there's only 1 nested object.
With more than 1 nested object, some weird positioning starts happening. 
Look at this updated codepen for an example of what I mean: https://codepen.io/kevgathuku/pen/zEGXNY?editors=1010

The nested `Group` component has the exact same `x` and `y` values, yet it gets positioned in a different place.

**Comment by lavrton** [comment]
@kevgathuku because the position of an element is always relative to the parent element.
If a group has pos x = 50, and shape inside this group has position x = 50, the absolute position of the shape will be 100 (50 + 50).

**Comment by kevgathuku** [comment]
Thanks once again. I'll put that in mind and try to come up with another solution

**Comment by alan345** [comment]
I Advise:

```
  dragEnd = e => {
    this.setState({
      x: e.target.x(),
      y: e.target.y()
    })
  }
```

and 

```
  render() {
    return (
      <Image
        name="rectange-name"
        x={this.state.x}
        y={this.state.y}
        width={50}
        height={50}
        fill="red"
        draggable
        onClick={this.handleClick}
        onDragEnd={this.dragEnd}
        image={this.state.image}
        onTransform={this.handleTransform}
      />
    );
  }
```
