### ISSUE TITLE
Filter for Konva Image

### ISSUE THREAD

**Issue by jericbas** [lavrton/react-konva#134]
Hello,

I'm not sure why filter is not working in Konva Image.  Do you have any idea?

`
    render() {
        return (
            <ReactKonva.Image
              filters={[Konva.Filters.Blur]}
              image={this.state.image}
            />
        );
    }
`

[http://jsbin.com/gibojosohu/edit?js,output](http://jsbin.com/gibojosohu/edit?js,output)

**Comment by lavrton** [comment]
You need to cache a node for using filters: https://github.com/lavrton/react-konva#using-filters

**Comment by jericbas** [comment]
Got it!
