### ISSUE TITLE
Crash trying to create multiple Rects

### ISSUE THREAD

**Issue by amatiasq** [lavrton/react-konva#136]
I'm having an issue here creating 1000 rects.

For 100 it works, but when I try to render 1000 it always fails randomly at generated line:

`_get(Object.getPrototypeOf(MyRect.prototype), 'constructor', this).apply(this, arguments);`

http://jsbin.com/jaxikobabu/edit?js,output

**Comment by lavrton** [comment]
This is infinite loop protection from jsbin. Take a look at the console.
You just need to add `// noprotect` to js source.
