### ISSUE TITLE
Scale Multiple Stages

### ISSUE THREAD

**Issue by ygorlf** [lavrton/react-konva#137]
Hi...

I have a scenario where I need do scale multiple stages, currently I use a Higher-Order-Component that generate for me all the stages and based on a wheel event I get the new scale and save on container component via setState then I pass that scale via props to all stages, the code It's working but the drawback is the slow performance because of the react flow (I think :()...

It's there another approach to pass that info to all stages or something in konva to improve that performance?

I set up a webpackbin to demonstrate the scenario:
https://www.webpackbin.com/bins/-KvVQyVv16El2mBmpb1i

If you zoom in or zoom out on the red boxes the zoom effect is not that fast, I think maybe I misunderstood the concept of scale on konva or react is not fast enough for that kind of scenario, any help are welcome...

**Comment by lavrton** [comment]
For me, the performance is almost ok. But there are "glitches" because of canvas size changes.
You can force synchoniuse stage draw on scale update:

```js
componentDidUpdate(oldProps) {
      if (oldProps.scale !== this.props.scale) {
        this.stage.getStage().draw();
      }
    }
```
Try to not change (or make it as rare as possible) size of stages. Because browser have to do a lot of work in this case (recalculate layout, etc).

**Comment by lavrton** [comment]
https://www.webpackbin.com/bins/-KvVzU94_2gQlnF8lCJR

**Comment by lavrton** [comment]
https://www.webpackbin.com/bins/-KvVzU94_2gQlnF8lCJR

**Comment by ygorlf** [comment]
thanks @lavrton, sadly my webapp needs that zoom feature, maybe I can use another zoom approach outside the konva context

**Comment by lavrton** [comment]
I think it is ok to use the zoom. Just try to debounce stage width update. For example, don't update it in real-time. Only once per second (for example).
