### ISSUE TITLE
Stop Child Event Propagation...

### ISSUE THREAD

**Issue by ygorlf** [lavrton/react-konva#139]
I have a draggable stage where other shapes are also draggable, how can I stop that drag shapes also fire drag on stage, I tried to set ev.evt.cancelBubble to true but unfortunately that doesn't work 
 :(

**Comment by lavrton** [comment]
What about just `ev.cancelBubble = true`?

**Comment by ygorlf** [comment]
Awesome, I think that the cancelBubble property inside the evt property should be modified :)

**Comment by callagga** [comment]
I just got caught out by this too...thanks

**Comment by oleole90** [comment]
For anyone reading this later being closed: Suppose you are just using 'onDragMove' in a child component and it's parent is calling onDragEnd bcz bubbling; give that child onDragEnd={e => (e.cancelBubble = true)} prop, even that child has no use for that event. Vice versa for similar cases.
