### ISSUE TITLE
Problem with stroke-width while plotting multiple Rect

### ISSUE THREAD

**Issue by abhishiv** [lavrton/react-konva#142]
Hey guys

**Problem**: `stokeWidth={1}` on a Rect doesn't seem to take effect when you are plotting multiple rectangles.

**Concise test case**: https://codesandbox.io/s/2jvo555lyj

**Visual Output**: 
![editor_-_codesandbox](https://user-images.githubusercontent.com/37350/32419554-cb16bef8-c2a1-11e7-8f1e-5c7d2db63c58.jpg)

This seems really weird, I noticed it at first because while plotting multiple Rect the stotke is really inconsistent. Am I missing some really obvious?

**Comment by lavrton** [comment]
Take a look here: https://stackoverflow.com/questions/13879322/drawing-a-1px-thick-line-in-canvas-creates-a-2px-thick-line

The first rectangle looks different, because it is near the edge of the canvas.

**Comment by abhishiv** [comment]
Thanks @lavrton. That helped me track it. Evidently svg suffers from it as well.

```export function smooth(val) {
  if (val % 1 === 0) return val + 0.5;
  return val;
}
```

Just for reference this helped me fix it. It just moves x/y coordinates by 0.5 when needed.

https://codesandbox.io/s/4195vxv74
