### ISSUE TITLE
React 16 upgrade issue - Initial image load only partially renders object (stroke but no image) 

### ISSUE THREAD

**Issue by bmoquist** [lavrton/react-konva#145]
My application can reconstruct a saved stage from a Redux store based on a previously saved stage's data. After upgrading to the new React-Konva 1.6.2 and React 16.1.1, the application only partially loads images when the trigger event occurs — showing the stroke but not the image. The render remains unfilled until another render event happens (e.g. an unrelated button click) — then, the images are immediately filled.

Prior to upgrade, loading images would first show the stroke and then automatically populate the image inside when it finished loading.

Here is an screenshot of the behavior with two images (~100-200kb each). 

Initial render:
<img width="557" alt="screen shot 2017-11-16 at 5 09 12 pm" src="https://user-images.githubusercontent.com/4001159/32922179-a317fe5a-caf6-11e7-8ed6-f6ef114260dd.png">

After another event occurs -- the images populate:
<img width="529" alt="screen shot 2017-11-16 at 5 09 21 pm" src="https://user-images.githubusercontent.com/4001159/32922186-a84638d8-caf6-11e7-97ba-d2376e3cf50f.png">

Loading the images and other related data to reconstruct the Stage takes place with multiple actions in a Redux Thunk. For images, the following is done for each image URL prior to be placement on the stage: 
```
let newImgObj = new window.Image()
newImgObj.crossOrigin = imageCrossOriginSetting
newImgObj.src = imageURL
```

Then, the image object is eventually passed into the standard Konva Image: 
```
  <Image
        ref=“image1”
        name={this.props.name}
        image={this.props.imgObj}
      	… other props
        />
```
After the image’s first render, this partial loading behavior generally goes away, and the image loads immediately (presumably from cache).

Is there a way to get the image's onload callback to trigger render when finished or another recommended means to overcome this so the images render automatically when they are ready as before prior to this upgrade?

Any suggestions/help would be appreciated -- thanks much!

**Comment by lavrton** [comment]
`react-konva` was rendering layer automatically on image load (in previous version). But I found some memory leaks with that code, so I removed it.
For now recommended way is to set `image` property to false value. Wait until the image is loaded, and only then set it to correct property. Take a look into the Readme: https://github.com/lavrton/react-konva#using-images

**Comment by bmoquist** [comment]
Got it - made the changes with no issues. Thanks for all your hard work on this project, Anton!
