### ISSUE TITLE
TypeError: Cannot read property 'ReactCurrentOwner' of undefined

### ISSUE THREAD

**Issue by kevgathuku** [lavrton/react-konva#147]
Hello @lavrton 
I'm getting this error in a `react-konva` project I'm working on.
```
Uncaught (in promise) TypeError: Cannot read property 'ReactCurrentOwner' of undefined
    at module.exports (react-reconciler.development.js:82)
    at Object.validateFormat (react-konva.js:449)
    at __webpack_require__ (react-konva.js:30)
    at Object.<anonymous> (react-konva.js:270)
    at __webpack_require__ (react-konva.js:30)
    at module.exports (react-konva.js:73)
    at react-konva.js:76
    at webpackUniversalModuleDefinition (react-konva.js:3)
    at Object.<anonymous> (react-konva.js:10)
    at __webpack_require__ (bootstrap 170b2960ef56b303039d:54)
```
`react-konva:  "version": "1.6.3"`
`konva": "^1.7.6",`
`"react": "version": "15.6.2"`
`react-dom "version": "15.6.2"`

Would you happen to have any pointers on what's happening or how to resolve it? 
Thanks in advance

Update:
On tracking down the bug, I traced it to this call 
`var ReactCurrentOwner = ReactInternals.ReactCurrentOwner;` inside `react-reconciler/cjs/react-reconciler.development.js`

**Comment by kevgathuku** [comment]
Pinning the version to `1.1.6` fixes it for me. Version 1.6.3 seems to have some breaking changes, causing that error.

**Comment by lavrton** [comment]
I just had a similar issue with my project. This error will happen if you use `React v15` with the last `react-konva v1.6.3`. `react-konva v1.6.3` is only for `React v16`, so it will not work with version 15.
Just make sure to lock minor version in `package.json`:
`"react-konva": "~1.1.6"`

**Comment by kevgathuku** [comment]
That was the issue for me too as I'm still on React 15. 
Thanks for following up 👍

**Comment by kevgathuku** [comment]
I'm also just wondering whether that should have been a major version bump.
The minor version change works with backwards compatible changes, and it seems this particular change was not  backward compatible with other 1.x versions.

**Comment by Fearless09** [comment]
This same issue is happening with Next version 15. Please, is there any fix for this

**Comment by keery** [comment]
Same issue with Next version 15

**Comment by lavrton** [comment]
May help: https://github.com/konvajs/react-konva/issues/817#issuecomment-2474508780

**Comment by Parth-12pm** [comment]
For Next js 15  (latest) and React 19 (beta)  this works fine 

```
    "konva": "^9.3.16",
    "next": "15.0.3",
    "react": "19.0.0-beta-26f2496093-20240514",
    "react-dom": "19.0.0-beta-26f2496093-20240514",
    "react-konva": "19.0.0-1",
```

**Comment by RobinD2ai** [comment]
> I use react konva 18.2.10 with react 18.3.1, and konva is 9.3.14, but i get > Error: Cannot read properties of undefined (reading 'ReactCurrentOwner'). The error is exactly import { Stage, Layer, Group } from "react-konva"; in this line. Can anyone help me please?

Did you manage to fix this?
