### ISSUE TITLE
"Warning: ReactDebugTool: debugID may not be empty" during render()

### ISSUE THREAD

**Issue by rscott78** [lavrton/react-konva#148]
I'm just trying this out and I've loaded up my environment with a simple example that I pulled from the demo.  Anytime the render method is called, I get the warning "ReactDebugTool: debugID may not be empty". I've put together a sample that forces a render when clicking on the stage; this click will cause the warning to be issued.  Can this be fixed?

```
onContentClick() {
    this.setState({someVar: 1});
}

render() {

   return <Stage width={700} height={700} style={{border:"1px solid black"}} onContentClick={this.handleCanvasClick}>
   <Layer>    
   </Layer>
</Stage>

```

**Comment by lavrton** [comment]
@rscott78 do you use `react v15`?
