### ISSUE TITLE
Uncaught TypeError: Cannot read property 'alternate' of undefined

### ISSUE THREAD

**Issue by tobi1449** [lavrton/react-konva#149]
I'm getting this error with the example code in the readme using the latest react-konva (1.6.4), konvajs (1.7.6) and react (16.1.1) versions with typescript:

```
Uncaught TypeError: Cannot read property 'alternate' of undefined
    at isFiberMountedImpl (react-reconciler.development.js:130)
    at isFiberMounted (react-reconciler.development.js:158)
    at findCurrentUnmaskedContext (react-reconciler.development.js:1091)
    at getContextForSubtree (react-reconciler.development.js:6861)
    at Object.updateContainer (react-reconciler.development.js:6941)
    at Stage.componentDidMount (react-konva.js:396)
    at vendor.js?v=OjVxDpV6p_Jfz2P38F_R2lc3pjVsUisUejeIABZq7AE:29697
    at measureLifeCyclePerf (vendor.js?v=OjVxDpV6p_Jfz2P38F_R2lc3pjVsUisUejeIABZq7AE:29508)
    at vendor.js?v=OjVxDpV6p_Jfz2P38F_R2lc3pjVsUisUejeIABZq7AE:29696
    at CallbackQueue.notifyAll (vendor.js?v=OjVxDpV6p_Jfz2P38F_R2lc3pjVsUisUejeIABZq7AE:18480)
```

**Comment by lavrton** [comment]
@tobi1449 can you create a simple `create-react-app` repository, so I can reproduce?

**Comment by tobi1449** [comment]
Hm, with a clean try it works, so it seems to be my environment. Sorry for bothering you :/

**Comment by crossSulation** [comment]
@tobi1449 I got the some issue, could you tell me how to fix it?

**Comment by flyon** [comment]
same error here, trying the basic example from the readme. No idea why or how to solve it.

**Comment by janoist1** [comment]
+1

**Comment by lavrton** [comment]
You need to match `react` and `react-konva` versions. `react-konva` depends on some react internals, so matching versions are important. If versions are not matching you must see a peerDependency warning in the terminal when you install `react-konva` with `npm` (probably `yarn` shows that warning too).

**The best way to solve the issue, is to install the lastest versions of `react`, `react-dom` and `react-konva`.**

```bash
npm install react@latest react-dom@latest react-konva@latest
```

If you don't want to upgrade react, you can use the lower version of `react-konva`.

```bash
npm install react-konva@16
```

**Comment by souldjl** [comment]
same error here, trying the basic example from the readme. i dont know how to reslove it 
 "react": "^16.13.0",
 "react-dom": "^17.0.2",
 "react-konva": "^16.8.6",
 "konva": "^8.3.5",
