### ISSUE TITLE
Help with text component

### ISSUE THREAD

**Issue by spiderhand** [lavrton/react-konva#152]
hi. first of all your lib is awesome =)

my problem is i want to change textBaseLine inside of Text component. is there any way to do so?

**Comment by lavrton** [comment]
You can't do this directly. As a workaround you can create Custom Shape and set required baseLine directly to context.

**Comment by spiderhand** [comment]
ok, i tried this way but it didn't work. how can i use existing component Text (which is very helpfull) and add textBaseLine?

```javascript
<Text
  x={x}
  y={y}
  text={text}
  fill={color}
  fontSize={size}
  fontFamily={'Roboto'}
  listening={listening}
  sceneFunc={function sceneFunc(context) {
    context.setAttr('textBaseline', 'ideographic');
    context.fillStrokeShape(this);
  }}
/>
```

**Comment by lavrton** [comment]
No. You can't use `sceneFunc` for buit-in shapes (like `Text`, `Rect`, etc).
There so no way to customize `textBaseline` for Text component. Only one way is to write 100% custom shape. Something like this:

```js
         <Shape
            x={50}
            y={50}
            text="Some text"
            fill="red"
            sceneFunc={function sceneFunc(context) {
              context.setAttr('textBaseline', 'ideographic');
              context.fillText(this.getAttr('text'), 0, 0);
            }}
            hitFunc={function hitFunc(ctx) {
              const text = this.getAttr('text');
              const { width } = ctx.measureText(text);
              ctx.beginPath();
              ctx.rect(0, 0, width, 10);
              ctx.fillStrokeShape(this);
            }}
          />
```

https://stackblitz.com/edit/react-omnjkv?file=index.js
