### ISSUE TITLE
Change default cursor to pointer

### ISSUE THREAD

**Issue by vaske** [lavrton/react-konva#156]
I'm looking for settings which will update default cursor to pointer once when user moves cursor over element, any settings like that?

**Comment by lavrton** [comment]
There are no builtin methods or settings. But you can implement it manually.

```js
        onMouseEnter={() => {
          document.body.style.cursor = "pointer";
        }}
        onMouseLeave={() => {
          document.body.style.cursor = "default";
        }}
```
https://codesandbox.io/s/nw8yjp76p0

**Comment by vaske** [comment]
Works perfect thanks :)
