### ISSUE TITLE
Stage doesn't have scale props in typescript

### ISSUE THREAD

**Issue by FriOne** [lavrton/react-konva#157]
This JSX:
```jsx
<Stage
            width={STAGE_WIDTH}
            height={STAGE_HEIGHT}
            scale={{x: scale, y: scale}}
/>
```
Produces the error:

> TS2339: Property 'scale' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Stage> & Readonly<{ children?: ReactNode; }> & Rea...'

But property exists, I can't understand how to make workaround, could you help me?
**typescript: 2.6.2**

**Comment by FriOne** [comment]
@lavrton could you update the npm package?

**Comment by lavrton** [comment]
@FriOne Done. Try it.

**Comment by FriOne** [comment]
@lavrton, it works, thanks. Good youtube channel you have, make a video about konva on it :)

**Comment by eddyLazar** [comment]
I have the same problem with npm package
