### ISSUE TITLE
IE 11 Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by RyM934** [lavrton/react-konva#162]
You're using Object.assign which isn't supported in IE 11. I noticed you're bundling your project with webpack. Would it be possible for you to also use the Babel runtime transform plugin to enable polyfill for IE?

This is the line of code that is causing exceptions in IE 11.
`module.exports = Object.assign({}, TYPES, { Stage: Stage });`

**Comment by lavrton** [comment]
Yeah. I think we should do it. Interesting in PR?

**Comment by RyM934** [comment]
Sure. Will do.
