### ISSUE TITLE
Animating on mount?

### ISSUE THREAD

**Issue by samosaboy** [lavrton/react-konva#165]
I want my shapes to animate forever on mount of my component, and I thought I could just do the following:

```
componentDidMount() {
    this.startAnimation()
}

private startAnimation = (): void => {
    const anim = new Konva.Animation(frame => {
      const scale = Math.sin(frame.time)/2
      this.circle.scale({ x: scale, y: scale })
    })
    anim.start()
}
```

However, the animation will trigger on mount but stop after about 5 - 6 seconds. I `console.log(frame.time)` in my `startAnimation` function and it's still logging way past 5 - 6 seconds. I'm wondering what the solution to this is?

**Comment by lavrton** [comment]
You need to set a layer for the animation. Try this:

```js
    const anim = new Konva.Animation(frame => {
      const scale = Math.sin(frame.time)/2
      this.circle.scale({ x: scale, y: scale })
    }, this.circle.getLayer());
    anim.start()
```
