### ISSUE TITLE
Animating svg path?

### ISSUE THREAD

**Issue by samosaboy** [lavrton/react-konva#170]
Is there no way to animate an svg path? I currently have:

```
<Path
x={-window.innerWidth / 6}
y={-window.innerHeight / 2}
opacity={0}
data={MapName}
name={'rippleEventMap'}
stroke={'#807775'}
strokeWidth={2}
rotation={0}
strokeScaleEnabled={false}
 scale={{
x: 6,
y: 6,
}}
/>
```

and `mapName` is just a huge string of characters I took from my SVG's data attribute.

and a custom tween animation, but it seems that there is nothing I can do to essentially fill the stroke of my svg path over a duration. Any ideas on what I can do here? Thank you~!

**Comment by lavrton** [comment]
@samosaboy what exactly do you want to animate? Color? SVG path (`data` attribute)?

**Comment by samosaboy** [comment]
Trying to animate the path itself (data). I have an outline of a map that I want to animate so the paths start at some random point and then create the map outline.

**Comment by lavrton** [comment]
Hmm. I don't know any good ways to animate `data`.

Only if you can create a function that will tween one `data` into another. But you have to do calculations manually.
