### ISSUE TITLE
 Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by rravithejareddy** [lavrton/react-konva#173]
I am getting error something like this " Cannot read property 'add' of undefined", when i a m using with react. see the below image for more.
![screenshot 110](https://user-images.githubusercontent.com/29831966/36364973-4fc55952-156d-11e8-9362-9b41a5a805b8.png)

**Comment by lavrton** [comment]
@rravithejareddy can you provide a demo?

**Comment by rravithejareddy** [comment]
Sure!

import React, { Component } from 'react';
import { render } from 'react-dom';
import { Stage, Layer, Rect, Text } from 'react-konva';
import Konva from 'konva';

class ReactKonva extends React.Component {
  state = {
    color: 'green'
  };
  handleClick = () => {
    this.setState({
      color: Konva.Util.getRandomColor()
    });
  };
  render() {
    return (
      <Rect
        x={20}
        y={20}
        width={50}
        height={50}
        fill={this.state.color}
        shadowBlur={5}
        onClick={this.handleClick}
      />
    );
  }
}
export default ReactKonva;


import React, { Component } from 'react';
import { connect } from 'react-redux';
//comps
import ReactKonva from './Frame/reactKonva.jsx'


class Flow extends Component {
    constructor() {
        super()
        this.refs = {
            canvas: {}
        }
        this.state = {
            zoomLevel: 100,
            zoomDropDownState: 0,
            imagesOnCanvas: []
        }

    }
 
    render() {
        return (
            <div>
              
                    <ReactKonva/>
                </div>
            
        );
    }

}



export default Flow;

**Comment by lavrton** [comment]
As I can see it is old `react-konva`. Can you try the last version?
