### ISSUE TITLE
perfectDrawEnabled property missing in typescript def

### ISSUE THREAD

**Issue by Valandur** [lavrton/react-konva#175]
The `perfectDrawEnabled` property https://konvajs.github.io/api/Konva.Circle.html#perfectDrawEnabled__anchor is missing on the `Circle` component (and I'm assuming on other shapes aswell). I'm not sure if this is missing on the side of konva or react-konva, since I'm not sure what they provide in typescript definitions

**Comment by lavrton** [comment]
Fixed in konva repo.
