### ISSUE TITLE
Konva warning: Can not change width of layer. Use "stage.width(value)" function instead

### ISSUE THREAD

**Issue by naivefun** [lavrton/react-konva#176]
I keep seeing this warning, not sure what's the cause, I simply used `<Stage width={500} height={500}></Stage>`

**Comment by lavrton** [comment]
@naivefun can you show a demo? Do you have something inside stage?

**Comment by naivefun** [comment]
@lavrton I was setting width/height on a Layer component and that's why. It was like this:
```jsx
<Stage width={100} height={100}>
  <Layer width={100} height={100}>
  </Layer>
</Stage>
```

I have removed attributes on Layer and the warnings go away.
