### ISSUE TITLE
typescript: StageProps are not complete

### ISSUE THREAD

**Issue by seethroughtrees** [lavrton/react-konva#177]
Konva allows several other parameters in the Stage element.  Including offsets, rotation etc...
https://konvajs.github.io/api/Konva.Stage.html

Unless I'm missing something.  We should allow StageProps to extend konva's NodeConfig instead of reproducing the params separately.  

Will attach a PR that updates in case its worth it for others.

**Comment by lavrton** [comment]
Thanks
