### ISSUE TITLE
Layer management with react-konva

### ISSUE THREAD

**Issue by RyM934** [lavrton/react-konva#179]
I want to do something like this demo: [Drag and Drop Stress Test](https://konvajs.github.io/docs/sandbox/Drag_and_Drop_Stress_Test.html). I basically want to move a shape or group to another layer for dragging. How do I best go about this with react-konva? I'm worried that by calling `moveTo()` react may update the parent component and it will move back to its declared layer.

**Comment by lavrton** [comment]
Demo: https://codesandbox.io/s/xv8kmkjkwp

**Comment by lavrton** [comment]
> I'm worried that by calling moveTo() react may update the parent component and it will move back to its declared layer

Correct. It is better to avoid calling `moveTo` manually. Use declarative way to detect the layer.

**Comment by RyM934** [comment]
Ah I didn't think about using `.startDrag()`. Thank you this was a life saver!
