### ISSUE TITLE
Clearing doesn't work itself.

### ISSUE THREAD

**Issue by Max-Starling** [lavrton/react-konva#183]
Hey, i have a problem.
I'm using react-konva in the project and every time when i navigate between pages, canvas doesn't clear itself.
So, i show you two screens(1-refresh page, 2-click a few times between pages).
I tried to fix it with 'ref', 'clear', 'clearReact' in componentWillUnmount, but this methods doesn't work too.
![image](https://user-images.githubusercontent.com/22237384/37410269-4d66026e-27b1-11e8-8ac4-0fb327f3cb61.png)
![image](https://user-images.githubusercontent.com/22237384/37410497-d4e9c31a-27b1-11e8-9c43-10af5115d518.png)

**Comment by Max-Starling** [comment]
Which is no less strange, i have one canvas element all the time.
![image](https://user-images.githubusercontent.com/22237384/37411043-edec7334-27b2-11e8-80e6-5578cc849f3c.png)

**Comment by lavrton** [comment]
What do you want to clear and why?

If you want to clear the canvas - just destroy all nodes (do not render elements in `render()` function).

**Comment by Max-Starling** [comment]
Sorry, it wan't problem of react-konva :)
Just didn't clear data arrays. 
Fixed.
