### ISSUE TITLE
Image does not work in Safari

### ISSUE THREAD

**Issue by alexwasner** [lavrton/react-konva#185]
I'm currently getting an IndexSizeError: The index is not in the allowed range on Safari. Works fine in Firefox and Chrome. I tried doing `new window.Image(100,100)` just to set an initial size on the image, but it still throws the error.

**Comment by alexwasner** [comment]
Here is an example from the demo. Works in Chrome. Does not work in safari https://codesandbox.io/s/1kn8xk1vq

**Comment by lavrton** [comment]
Looks like Safari can't draw an image that is not loaded yet. Try to set image only after it is loaded.


https://codesandbox.io/s/ppzp7ylloj

**Comment by chlela** [comment]
@lavrton https://codesandbox.io/s/ppzp7ylloj gives 404 error. Any chance you can post the workaround here or send a new codesanbox. I'm facing the same issue and I followed similar code as here https://codesandbox.io/s/github/konvajs/site/tree/master/react-demos/images?from-embed yet Safari still crashes 
Thanks
