### ISSUE TITLE
Dynamic page loading failed TypeError: Cannot read property 'ReactCurrentOwner' of undefined

### ISSUE THREAD

**Issue by chuanshuogod** [lavrton/react-konva#186]
# Steps to reproduce

create a Component

```
import React from 'react';
import { render } from 'react-dom';
import { Stage, Layer, Rect, Text } from 'react-konva';
import Konva from 'konva';

class Canvas extends React.Component {
  render() {
    return (
      <div>
      </div>
    );
  }
}

export default Canvas;
```

but when loading the page, I got below error:

**Comment by ejarzo** [comment]
It seems like this issue usually has to do with `node_modules` confusion or the versions of your modules. Without additional context, I would say try deleting `node_modules` and running `npm install`. Make sure you are installing correctly with your version of React: https://github.com/lavrton/react-konva#installation

A couple other things - Is there any reason you are importing from both `konva` and `react-konva`? You also do not need to import `render` from `react-dom` to be able to define a component's render method. Also, it doesn't look like you are returning anything from your component's `render` function, which React doesn't allow. Hope that helps!

**Comment by lavrton** [comment]
As I can see you are trying to render `<div>` into a stage. `react-konva` doesn't support such drawing.

**Comment by chuanshuogod** [comment]
Importing some from "react-konva" is error.    
I 'm not  render <div> into a stage

**Comment by chuanshuogod** [comment]
Importing some from "react-konva" is error.
I 'm not render _<div>_ into a stage

**Comment by chuanshuogod** [comment]
Importing some from "react-konva" is error.
I 'm not render   `div`   into a stage

**Comment by lavrton** [comment]
@chuanshuogod can you make a demo? You can use this for bootstrap: https://codesandbox.io/s/k31j2jjxov

Or use something else. Also check versions. Try to use the last one.

**Comment by chuanshuogod** [comment]
I can use version 1.1.4, but 1.7.1 can't.
![image](https://user-images.githubusercontent.com/32629589/38191079-b94ba32a-3699-11e8-9d11-91aa2e2e00f2.png)
![image](https://user-images.githubusercontent.com/32629589/38191091-c5ad3e8a-3699-11e8-99a4-adfb6aa2c037.png)

**Comment by chuanshuogod** [comment]
![image](https://user-images.githubusercontent.com/32629589/38191605-fff6a052-369b-11e8-9186-0f209f8bb826.png)
My English is not good .
Thanks for your help

**Comment by lavrton** [comment]
I think there is `react` and `react-konva` versions mismatch.

**Comment by chuanshuogod** [comment]
OK!You are right!!!!
I'm so foolish~~~~~
Thank you very very very much~!!!(^_^)

**Comment by merges** [comment]
@lavrton What is the mismatch? What should the correct versions be? (Is this documented somewhere?) I'm running into the same bug with React 16.
