### ISSUE TITLE
How to store stage as jons like konva offer for stage? I can't see the function `.toJson` on the stage node

### ISSUE THREAD

**Issue by adamchenwei** [lavrton/react-konva#191]
<img width="429" alt="screen shot 2018-04-18 at 11 29 40 am" src="https://user-images.githubusercontent.com/4201698/38942053-d639690e-42fb-11e8-8e3c-36d7dd2e62cf.png">

**Comment by lavrton** [comment]
You can take a look in Readme. Getting `Konva.Stage` instance works a bit different:

```js
const stage = this.stageNode.getStage();
const json = stage.toJSON();
```
