### ISSUE TITLE
this.textNode.getWidth() always stay the same width, even when the text in it is changed. anyway to make the width also update itself according to the new text udpated in <Text> ?

### ISSUE THREAD

**Issue by adamchenwei** [lavrton/react-konva#193]
this text node will be something like this

```
<Text
                ref={node => {
                  this.textNode = node;
                }}
                //x={10} y={10}
                //padding={16}
                text={`111 1 1 1 1 1x: ${this.state.x} y: ${this.state.y}`}
                align={'center'}
              />
```

**Comment by adamchenwei** [comment]
to play with an example
https://github.com/adamchenwei/konva-react-playground

**Comment by lavrton** [comment]
Your demo works ok for me: https://codesandbox.io/s/wynkp3qy0k

What is not correct for you?

**Comment by adamchenwei** [comment]
@lavrton so try these steps

1. move text to random places
2. click save coordinate
3. now see the text get larger, note that there is call to set width state again, but the width got picked up by the function will still be the same textwidth before text gets longer
4. see the dotted Rect overlap partially with the text

**Comment by lavrton** [comment]
`setState` is an async function. See https://reactjs.org/docs/react-component.html#setstate.

Calling `setWidth` immediately after `setState` will use old data because the component is not updated yet. You should use a callback for `setState`.


```js
this.setState(
      {
        x: newX,
        y: newY,
        savedCoordinates: {
          x: newX,
          y: newY
        }
      },
      () => this.setWidth()
    );
```

https://codesandbox.io/s/wynkp3qy0k
