### ISSUE TITLE
unable to add contextMenu(right click option) on an image.

### ISSUE THREAD

**Issue by arsam31** [lavrton/react-konva#198]
can you please tell me how can i addright click option on an  image.I'm using react-konva..whenever i try to wrap the image in contextmenu tag.it says "divs are not supported in konva".Whats wrong I'm doing??

**Comment by lavrton** [comment]
@arsam31 what is a contextmenu tag?

You may just need this:

```
          <Rect
            x={20}
            y={20}
            width={50}
            height={50}
            fill="red"
            shadowBlur={5}
            onContextMenu={(e) => {
              // do not show native context
              e.evt.preventDefault();
              console.log('context')
            }}
          />
```
https://codesandbox.io/s/24m49792nn

**Comment by ZikDead** [comment]
found bug, onClick event fires with onContextMenu event.

**Comment by lavrton** [comment]
@ZikDead can you add more info about your issue?

**Comment by ZikDead** [comment]
@lavrton https://codesandbox.io/s/5k8m6w608l

**Comment by lavrton** [comment]
That is not a bug. Clicking with the right mouse button for a context menu is still a "click". You can use `e.evt.button` to filter those cases.

**Comment by destumme** [comment]
@lavrton I found this behavior to be confusing. Vanilla js click handlers do not trigger in this way, a contextmenu event does not trigger a click event when setting up standard 'click' and 'contextmenu' listeners directly on dom elements. Checking an event based on button could lead to accessibility problems if a user has the buttons on their mouse configured to be a different order than the default.

**Comment by lavrton** [comment]
It is a bit different from DOM events, but I don't see any issues here.

> a contextmenu event does not trigger a click event when setting up standard 'click' and 'contextmenu' listeners directly on dom elements

The `click` will NOT trigger on konva nodes if you don't call `e.preventDefault()` inside `contextmenu`. So by default it will work exactly the same as in DOM.

**Comment by destumme** [comment]
Maybe I'm not explaining quite right. Here is a codesandbox describing the behavior in vanilla js. 

https://codesandbox.io/s/modern-worker-4q4wv?file=/src/index.js

Both the event listeners call e.preventDefault(). The contextmenu event does not trigger the click event handler. Not calling e.preventDefault to me seems to defeat the purpose of having a contextmenu handler. My goal is to display a menu in the canvas on contextmenu events. (CTRL+click and right click). Which requires having preventDefault() called, otherwise the browsers context menu will show in addition to my custom menu.

**Comment by lavrton** [comment]
So what do you suggest?

**Comment by destumme** [comment]
That the behavior is the same as the vanilla js. 

I was able to get around the issue for attaching event handlers to a div wrapping the whole stage (which will work for contextmenu's in open space on the canvas), but that workaround is not sufficient for event handlers on individual svgs rendered in the canvas directly. contextmenu events do not natively fire click events, so I would expect that same behavior in this konva.
