### ISSUE TITLE
detect rerender

### ISSUE THREAD

**Issue by seeden** [lavrton/react-konva#199]
is it possible to handle rerender?
I am trying to catch rerender after image load. But it is not working with just forceUpdate. I can not see any "onRender" callback of the react-konva

**Comment by lavrton** [comment]
What is your use case? Can you give more info?

**Comment by seeden** [comment]
Sure.
I am using a lot of react-konva on my page. After all images are loaded I am doing toDataUrl and showing just <img> instead of react-konva.(because performance on mobile with infinity scroll) I am not able to get finall canvas with all images. Sometimes I will get rendered all images sometimes no.

**Comment by seeden** [comment]
It is working. Thanks for the idea
