### ISSUE TITLE
Konva warning: Node has no parent. zIndex parameter is ignored.

### ISSUE THREAD

**Issue by adamchenwei** [lavrton/react-konva#202]
the error is not true though. zIndex did take effect. in the layers order. What exactly is ignored? I feel there maybe a need for more info?

Thanks

**Comment by lavrton** [comment]
I guess it didn't take effect on the first rendering. It may take effect later.

I suggest avoiding usage of `zIndex` property.
https://github.com/lavrton/react-konva/issues/194

**Comment by lavrton** [comment]
https://konvajs.org/docs/react/zIndex.html
