### ISSUE TITLE
Rect node doesn't have contains function

### ISSUE THREAD

**Issue by PabloSzx** [lavrton/react-konva#205]
I am trying to set up a modal over a rectangle shape, and i can't handle the click because the event emits the function contains  " [HTML DOM contains() Method](https://www.w3schools.com/jsref/met_node_contains.asp) " and the node rendered by this library doesn't have the function

[https://i.imgur.com/qCRWOww.png](https://i.imgur.com/qCRWOww.png)

**Comment by lavrton** [comment]
`react-konva` nodes are not DOM elements. It is a virtual representation of canvas state. All methods are defined in konva API doc: https://konvajs.github.io/api/Konva.html
