### ISSUE TITLE
Vertical align Text

### ISSUE THREAD

**Issue by yannickl** [lavrton/react-konva#207]
Hi,

I have a fixed header where I would to vertical align my title in the middle. I don't figure out how to do that easily. I've found this closed pull request (https://github.com/konvajs/konva/pull/354) but it does not help me...

<img width="974" alt="screen shot 2018-05-30 at 18 39 55" src="https://user-images.githubusercontent.com/798235/40734682-6c33f72c-6439-11e8-8ff7-e30da4aaee8d.png">

Have you any hints?

**Comment by lavrton** [comment]
```
// align inside this height
const HEIGHT = 100; 
const textHeight = text.height();

text.y((HEIGHT - textHeight) / 2);
```

http://jsbin.com/tikehiwina/1/edit?js,output

**Comment by yannickl** [comment]
@lavrton thank you for your quick answer. I would know if it was possible to vertical align the text without to add some state variable to be able to calculate the middle?

**Comment by lavrton** [comment]
Currently, there is no way to do this. I have to do some calculations in your component methods and update state.

Probably one day `Konva` will support vertical-align.

**Comment by yannickl** [comment]
@lavrton as I already know the header's height (this is a fixed size and position), I managed to write it in one line:

```jsx
<Text 
   text="title" fontSize={45} fill="#FFF" x={20} width={80} align="center"
   ref={node => { node && node.y(20 + (100 - node.getHeight()) / 2); }}
/>
```

Thank you again for the hints!
