### ISSUE TITLE
Add Layer to Stage

### ISSUE THREAD

**Issue by PepeFiStach** [lavrton/react-konva#209]
Hello, I have problem with layer, i would like to create layer management, when user click button the layer is added to Stage, but this does not work, when i create file in createsandbox this work, but in my code no, i don't have idea why.

code is simple : 
        let layer = new Konva.Layer();
        this.stage.getStage().add(layer);

and this does not work.

**Comment by PepeFiStach** [comment]
I fixed my issue.

**Comment by srisaiswaroop** [comment]
Can you please share the fix? I am facing same issue and could not find anything in the documentation for react.

**Comment by PepeFiStach** [comment]
I don't remember but I think I forgot to update stage, try this.stage.getStage().draw()
