### ISSUE TITLE
Drawing Line by changing its points

### ISSUE THREAD

**Issue by mattkauffman23** [lavrton/react-konva#210]
I'm running into an issue where Lines are not updating when their points change. I set the `x`, `y` of the Line component to `0` and when drawing begins I set the `points` array to initially be the mouse's coordinates as the starting and finishing points of the line. Then as the mouse moves I update the `points` array such that the current mouse position is the second point. So something like this: `[startMouseX, startMouseY, currentMouseX, currentMouseY]`. Unfortunately the line on the canvas doesn't update. I'm using redux to handle state and persisting it. When I reload the line is actually where I expected it to be. At first it looked like maybe the component wasn't rendering but I put some logs in `render` and took a look in the react dev tools and the react bits appear to be updating correctly. As a hack I changed things up to trash the line and create a new one on each mouse event but I'd prefer not to have to do that. Any ideas on what I might be missing or hints on how to debug further?

**Comment by lavrton** [comment]
@mattkauffman23 can you make a small demo?

**Comment by mattkauffman23** [comment]
And when I created a small demo it did work as expected. Turned out that the issue was in my own code. I was caching shapes and only updating the cached version when specific props changed and I hadn't added `points` to that list of props! Apologies for opening an issue before creating an isolated test case. And thanks for the quick response.
