### ISSUE TITLE
Working with large sets of nodes

### ISSUE THREAD

**Issue by Bobvantpadje** [lavrton/react-konva#211]
This is more a question than an actual issue,

Im creating a canvas on which I can add nodes and I can connect those nodes with lines. The nodes have an x and y value to determine where it should be positioned. I store al these nodes in an array in my state.
I also have an array of `lines`, these lines contain two objets, a `parentNode` and a `childNode`. I use these properties to determine to which points I should draw my line. 

To update a `node` and it's corresponding `line` I loop through all the `nodes` in my state and then update the correct node. And then I also have to loop through al my `lines` and update the correct line as well. 

This works fine, but when working with larger datasets it gets a little laggy because it has to loop through the whole array of `nodes` and `lines` all the time. Do you have any suggestions on how I can improve the performance?

**Comment by lavrton** [comment]
My suggestion is:

1. Store nodes in Object, not in the array.
```
const nodes = {
  nodeId1: {x, y},
  nodeId2: {x, y}, 
}
```

2. In lines save reference to the nodes by id:
```
const lines = {
   lineId1: { startNode: 'nodeId1', endNode: 'nodeId2'}
}
```

3. When you need to update a node you don't need a long loop, just update required object
4. You don't need to update a line, because you calculate its coordinates dynamically with id reference.

**Comment by Bobvantpadje** [comment]
What you suggested works fine, but one problem I do still have is that whenever a `node` changes, the whole component will rerender because my render method just loops through all the `nodes` and `lines` I have in my `state`. Is there a way to just rerender the `node` and `lines` that actually changed?

**Comment by lavrton** [comment]
It really depends on your code and store structure. But if you can use https://mobx.js.org/ updating only one component will be super easy.

**Comment by lavrton** [comment]
https://blog.lavrton.com/how-to-optimise-rendering-of-a-set-of-elements-in-react-ad01f5b161ae
