### ISSUE TITLE
onTransform on Rect missing in typescript def

### ISSUE THREAD

**Issue by medslt** [lavrton/react-konva#213]
According to documentation https://konvajs.github.io/docs/select_and_transform/Transform_Events.html  there should be an onTransform  on the Rect component, and this works when not using typescript.

But when using typescript  the compiler reports:
Property 'onTransform' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Rect> & Readonly<{ children?: ReactNode; }> & Rea...'

Looking at https://github.com/lavrton/react-konva/blob/dff2ffa378d597790d70eae415ba3cac816b32bf/react-konva.d.ts#L5-L22 this actually seems to be missing.

**Comment by S-Eddine** [comment]
Have the same problem here! 👍

**Comment by lavrton** [comment]
Can some create a Pull Request?

There is also `transformstart` and `transformend` events.

**Comment by medslt** [comment]
@lavrton  I created a Pull Request

**Comment by S-Eddine** [comment]
Great, thx ! @medslt

**Comment by lavrton** [comment]
Published.

**Comment by medslt** [comment]
Thnx @lavrton
