### ISSUE TITLE
Can't use style on all elements

### ISSUE THREAD

**Issue by Bobvantpadje** [lavrton/react-konva#216]
Let me first start of saying that I love React Konva! 

One thing that's not really clear to me is when I can use regular CSS on Konva elements. I styled my 'Stage' with pure CSS and this work perfectly, but when I'm trying to style my `Group` it doesn't effect the styling at all. It's not really clear to me on what Elements I can use regular CSS and for which one I have to add the styling as props to the component.

**Comment by lavrton** [comment]
**You can use CSS only for `Stage` component**.

Stage has root `<div>` DOM element. We can apply styles here.
All other elements are not DOM elements. They are virtual Konva nodes. We can't apply CSS to Konva nodes.
