### ISSUE TITLE
pointerAtBeginning is not part of Arrow constructor parameters

### ISSUE THREAD

**Issue by dropbeardan** [lavrton/react-konva#218]
Attempting to create an Arrow with the property pointerAtBeginning will throw a TypeScript error that the property does not exist.

The method is listed as a property in the Arrow class on konva.d.ts however it is not listed on the ArrowConfig constructor.

The property still exists on vanilla Konva according to the docs: https://konvajs.github.io/api/Konva.Arrow.html

**Comment by lavrton** [comment]
Fixed with https://github.com/konvajs/konva/commit/7400977f50672bea99b56e8cf6a95433634e410b.
I will publish later. Thanks for the report.
