### ISSUE TITLE
Complex Text Example

### ISSUE THREAD

**Issue by juliuszc** [lavrton/react-konva#29]
I ran into a problem trying to recreate this example from the konva website. 
http://konvajs.github.io/docs/shapes/Text.html

The nesting of the text inside of the rectangle doesn't work. However, if I render them separately the text shows up fine.
http://jsbin.com/kukibo/edit?js,output

**Comment by lavrton** [comment]
This is expected behaviour.
Shapes (such as `Rect`, `Circle`, `Image`, etc) can not have children elements. Only `Stage`, `Layer` and `Group` can have nested elements.

Probably it will be better to add warning message when user trying to add child element into `Shape` node.
