### ISSUE TITLE
JSC support

### ISSUE THREAD

**Issue by grimcoder** [lavrton/react-konva#3]
This is not really an issue but more like a suggestion. That would be great if this tool could generate a Canvas code based on the given JSX React components (e.i. converting JSC DOM to Canvas elements). I know this is lots of work.

**Comment by lavrton** [comment]
It is possible to generate canvas with `react-konva` and then call `stage.toImage()`.
I am not sure what is "canvas code".

I am closing this issue for now, as I think it is not useful in this lib.
Reopen if you think otherwise.
