### ISSUE TITLE
ReactKonva.Image component needs a fully loaded Image() object to work

### ISSUE THREAD

**Issue by fmobus** [lavrton/react-konva#4]
It took me a while to figure this out, and I ended up resorting to ugly timeout hacks and forced re-renders of the component. 

Would it be possible to tie the image object onload event to the redrawing of the shape? Or should ensuring image is fully loaded be the user's responsibility?

**Comment by lavrton** [comment]
Right. It should be part of `konva-react`. I will take a look soon.

**Comment by lavrton** [comment]
Fixed in v0.6.2
