### ISSUE TITLE
Problem with Canvas

### ISSUE THREAD

**Issue by mfeuermann** [lavrton/react-konva#40]
Hello, i have problem with building Meteor app. 
I still receiving message

Unable to resolve some modules:
  "../build/Release/canvas"

Can you help me with this problem? I have finished application and big problem with this issue, cause im not able to deploy this app to production!

Thank you

**Comment by ixjakub** [comment]
The same. :/

**Comment by lur9622** [comment]
I have the same problem :D ... someone now how to configure new version meteor to react-konva ... ?

**Comment by lavrton** [comment]
I hope it is fixed now.
I am not sure how meteor work in server side.
