### ISSUE TITLE
Not compatible with new version of React (15.4.0)

### ISSUE THREAD

**Issue by twobit** [lavrton/react-konva#44]
Latest React (15.4.0) doesn't expose internals through `react/lib` anymore:

```
modulesModuleNotFoundError: Module not found: Error: Cannot resolve module 'react/lib/ReactInstanceMap'
```

From [React blog](https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html):

> However, there is a possibility that you imported private APIs from react/lib/*, or that a package you rely on might use them. We would like to remind you that this was never supported, and that your apps should not rely on internal APIs. The React internals will keep changing as we work to make React better.

**Comment by lavrton** [comment]
Fixed. Thanks for the report. Unfortunately, I don't know any ways for implementation of `react-konva` (or any other similar libs) without using React's private modules.

Close by https://github.com/lavrton/react-konva/commit/d4837afaaf37ba043d2066e7b3b3c05975a78783

**Comment by twobit** [comment]
Thanks for the quick update. Is peer dependency of `~15.5.0` a typo?

**Comment by lavrton** [comment]
@twobit ah. that was typo. should be fixed now.

**Comment by Guria** [comment]
Any plans to workaround it? 16.0 is coming and only react-konva in our app prevents us to update.

**Comment by lavrton** [comment]
@Guria `react-konva` will be updated to work with react 16. 

Currently, I don't have any plans to update the lib until react v16 official publish.

**Comment by twobit** [comment]
There's a new thread about the [React 16 beta](https://github.com/facebook/react/issues/10294):

> There is no react/lib/* and react-dom/lib/* anymore. Even in CommonJS environments, React and ReactDOM are precompiled to single files ("flat bundles"). If you previously relied on undocumented React internals, and they don't work anymore, **let us know about your specific case in this issue**, and we'll try to figure out a migration strategy for you.

Maybe somebody over there has ideas on how to migrate to a non `react/lib` approach.
