### ISSUE TITLE
How to dynamically add Image to layer? ... question

### ISSUE THREAD

**Issue by Dudyboy** [lavrton/react-konva#46]
I want to have clean canvas at the begining and I want to add drag and drop images to canvas layer. How can I do this?

Thanks for reply :)

**Comment by lavrton** [comment]
http://jsbin.com/voguciqete/1/edit?js,output

**Comment by Dudyboy** [comment]
Sorry for email ... thanks form reply anyway :)

I want to do equivalent tihs in react-konva:

http://stackoverflow.com/questions/33359214/clicking-on-array-of-images-to-add-them-to-konva-stage

Acctualy, I do not know how to do this yet, so I will be thankful for any help.
