### ISSUE TITLE
A pixel is not a pixel

### ISSUE THREAD

**Issue by matthewoates** [lavrton/react-konva#48]
Many devices scale web content, so that what the browser naively thinks of a pixel could be 2x2, 3x3, etc pixels instead.

see: http://alistapart.com/article/a-pixel-identity-crisis

What this means for this library, is that graphics will not be rendered with optimal fidelity for any iOS, Retina MacBook, modern Android phone, etc.

**Comment by matthewoates** [comment]
Will investigate further and move to `konva`

**Comment by lavrton** [comment]
@matthewoates you don't need. Konva already supports HDPI devices (like retina).

**Comment by matthewoates** [comment]
Yep. Just discovered that. Thanks for the quick response.
