### ISSUE TITLE
Stage dragging

### ISSUE THREAD

**Issue by burningPotato** [lavrton/react-konva#5]
Hi, according to http://konvajs.github.io/docs/drag_and_drop/Drag_a_Stage.html,  it is possible to drag the Stage. 

I tried the same thing with react-konva (code below) and it seems not working. Nothing is happening, drag events aren't firing etc.

Am I doing anything wrong or is it not working the same way in react-konva  ?

I'm using  react-konva v. 0.6.4 (cause I need react v0.14 in my project).

```javascript
import React, {Component} from 'react';
import {Layer, Stage, Circle} from 'react-konva';

export default class Example extends Component {

  handleDragStart = () => {
    console.log('dragStart');
  };

  render() {
    var width = window.innerWidth;
    var height = window.innerHeight;
    return (
      <Stage
          container = {'container'}
          width = {width}
          height = {height}
          draggable = {true}
          onDragStart = {this.handleDragStart}
      >
        <Layer>
          <Circle
              x = {width / 2}
              y = {height / 2}
              radius = {70}
              fill = {'red'}
              stroke = {'black'}
              strokeWidth = {4}
          />
        </Layer>
      </Stage>
    );
  }
}
```

**Comment by lavrton** [comment]
Right. `react-konva` doesn't support such properties for `Stage`. But it should. We can fix it in the current version. As workaround, you can set `draggable:true` for `Layer` (behaviour will be almost the same if you have just one layer).

**Comment by burningPotato** [comment]
thx for the prompt reply

**Comment by lavrton** [comment]
Fixed.
