### ISSUE TITLE
No graphics drawn if ReactDOM.render is delayed (setTimeout)

### ISSUE THREAD

**Issue by UrKr** [lavrton/react-konva#50]
I'm planning on rewriting some code in react-konva, and I noticed that it wasn't drawing anyting. 
I tried the demo, and it seems that the problem might be a delayed call to ReactDOM.render. 

No canvas appears in the dom tree.

I added this to the demo: 
```
setTimeout(function(){
    ReactDOM.render(<App/>, document.getElementById('container'));
}, 1000)
```

http://jsbin.com/saxipodado/edit?js,output

**Comment by lavrton** [comment]
It is just some jsbin magic with protecting.
`// noprotect` solve the issue
http://jsbin.com/herafoxudo/edit?js,output

**Comment by UrKr** [comment]
I see. So it must have been something else in my project.
