### ISSUE TITLE
Filters on Image

### ISSUE THREAD

**Issue by stanwilsonjr** [lavrton/react-konva#51]
Getting this error when I try to apply a filter to an image after upload.

konva.js:1115 Konva error: Unable to apply filter. Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation

As you can tell i'm doing a lot of things here but between the font loading and image loading i'm not sure when to cache my image.

```
const globalKonva = window.Konva;


class WodCanvas extends Component {
  constructor(props){
    super(props);
    this.state = {
        image: this.props.img,
        font: 'Montserrat:700'
      }

    }

    componentwillmount(){}
    componentDidUpdate(prevProps, prevState){
      if(prevProps.img !== this.props.img){
        this.updateCanvas();
      }
    }
    componentDidMount() {

      this.updateCanvas();
    }

  updateCanvas(){
          const image = new window.Image();
          const imgSrc = this.props.img;
          WebFont.load({
            google: {
              families: ['Rubik One','Roboto','Montserrat:700']
            },
            active: function() {
                image.src = imgSrc;
            }

          });

          image.onload = () => {
            this.wodimage.cache();

            this.setState({
              image: image,
              font: 'Montserrat'
            },()=>{
              this.image.cache();
            });
          }

  }



  render(){

      return (
        <Stage width={500} height={500} className="wodcanvas" >
         <Layer >
             <Rect filters={[globalKonva.Filters.Noise]} noise={1}  x={0} y={0} width={500} height={500} fill="red"  ref={(node) => { this.rect = node;}} />

            <Image filters={[globalKonva.Filters.Blur]} blurRadius={5}   opacity="0.25" width="500" height="500"   image={this.state.image} ref={(node) => { this.image = node;}}   />
             <Text x="20" y="20"  fontSize="75" fill="#FFFFFF" text={ this.props.txt } fontFamily='Montserrat' />
            <Text x="20" y="125" lineHeight="1.25" width="300" fontSize="20" fontFamily='Roboto'  fill="#fff" text={ this.props.content }/>


          </Layer>
       </Stage>
     )
  }

}



```

**Comment by lavrton** [comment]
@stanwilsonjr I never had such error. What size of your image?

**Comment by stanwilsonjr** [comment]
@lavrton  500 x 500  
Am i caching in the right places?


With that in mind i may try a smaller size

**Comment by lavrton** [comment]
Hmm. I need to explore that problem.
I created a demo http://jsbin.com/hofabewulu/edit?js,output
Work ok in firefox, but the same issue in Chrome.

**Comment by stanwilsonjr** [comment]
@lavrton  So its an issue with chrome, Here is what I've found so far.. 

https://stackoverflow.com/questions/40822573/javascript-canvas-ctx-getimagedata-running-out-of-memory
http://stackoverflow.com/questions/16758020/javascript-memory-leak-with-html5-canvas-getimagedata-in-chrome-browser-for-mac

Hope this helps. Meanwhile I'll continue to chip away at it on my side

**Comment by stanwilsonjr** [comment]
Ok so figured it out.
If when you try to cache the canvas if let unset the SceneCanvas width and height default to 50,000,000 each
![scenecanvas](https://cloud.githubusercontent.com/assets/515121/21084988/858eb942-bfd9-11e6-8820-eae6f20b9f86.png)

So its really a matter of setting the cache w/h to a manageable size. 

```
// Works
this.wodimage.cache({width:500,height:500 });


```
Maybe setting the default width/height for cache may help?

**Comment by lavrton** [comment]
@stanwilsonjr 
Ah. I found the problem now. I didn't notice it in the source in first time.
So you are setting attributes as strings: `width="500" height="500"`, but `react-konva` do not convert it into numbers. Just use numbers: `width={500} height={500}`

**Comment by stanwilsonjr** [comment]
@lavrton  works. thanks man
