### ISSUE TITLE
Scale whole canvas?

### ISSUE THREAD

**Issue by FezVrasta** [lavrton/react-konva#53]
Hi,

I'm trying to scale the whole canvas in a way that the internal elements will be scaled as well.

Is it something provided out-of-the-box with react-konva?
I found the Transform class in Konva but I don't find a way to make it work with React.

I thought this would work:

```
<Stage>
  <Transform>

  </Transform>
</Stage>
```

But React complains because Transform isn't exposed by react-konva.

**Comment by lavrton** [comment]
@FezVrasta 
```javascript
<Stage scaleX={0.5}>
  <Layer>
   {/* Your shapes */}
  </Layer>
</Stage>
```
You can set `scaleX` and `scaleY` for any node (Stage, Layer, Group or any Shape)

**Comment by FezVrasta** [comment]
😱 Thank you so much! You saved my day.

**Comment by esseswann** [comment]
It seems that setting scale on the stage doesn't affect inner shapes

**Comment by lavrton** [comment]
@esseswann can you create a demo?
This one works fine: http://jsbin.com/tifabaniva/1/edit?js,output

**Comment by developdeez** [comment]
Any suggestions to use scaling on Mobile within the Stage component?

**Comment by lavrton** [comment]
See the answer above. Use `scaleX` and `scaleY` for a stage.

**Comment by developdeez** [comment]
https://github.com/konvajs/react-konva/issues/400
