### ISSUE TITLE
what make the bad performance?

### ISSUE THREAD

**Issue by jy1989** [lavrton/react-konva#54]
Hello. thank you for this nice library.

I've made a demo use react-konva, here is the online demo:

http://jy1989.github.io/demo/react-canvas-gol/

and  the code

https://github.com/jy1989/react_game_of_life/blob/react-canvas/app/index.js

so I have no idea why the performance so bad

How can I check?

**Comment by lavrton** [comment]
So first I think you have too many rectangles. Probably if you will draw a black background and draw ONLY red cells performance will be much better.
Then if you don't need interactivity (pointer events), you should set:
```
<Layer hitGraphEnabled={false}>
```
This tip will improve performance twice.

**Comment by lavrton** [comment]
If it is still not enough - I suggest not to use React and not to use Konva, or any other library for canvas drawing. And draw into canvas manually via native context. I am 100% sure performance in this case will be super duper cool.

**Comment by jy1989** [comment]
Thank you for your suggestion! that's very helpful 

that's what I made something for fun and learn about react. 

so I will try to update my code as you said.
