### ISSUE TITLE
Compatibility with preact?

### ISSUE THREAD

**Issue by FezVrasta** [lavrton/react-konva#55]
Seems like you use a lot of private methods and APIs that aren't exposed by `preact-compat` (and, by the way, shouldn't be used neither with React since they are private).

Do you have plans to move the code to a full public-API code?

**Comment by lavrton** [comment]
Currently, I don't know any other ways for `react-konva` implementation without using `react`'s internals. I will be happy to move to full public API. I hope one day `react` will have such option for custom renderers (not DOM).
