### ISSUE TITLE
Dynamic Size

### ISSUE THREAD

**Issue by ZephD** [lavrton/react-konva#57]
Anyway to get the Stage width and height to fit it's container?
e.g. <Stage ref={(s) => { this.stage = s; }} width={'100%'}>

Can the children also therefore react to the width and height of the stage?
e.g. <Image width={this.stage.width / 2} />

**Comment by lavrton** [comment]
Currently no. You have to calculate parent container size by yourself and manually set stage size.
You need to move children, you can set a scale to the stage.
