### ISSUE TITLE
Image not defined (testing using jsdom)

### ISSUE THREAD

**Issue by ZephD** [lavrton/react-konva#60]
https://github.com/lavrton/react-konva/blob/master/src/react-konva.js#L224

This line of code expects "Image" to exist on the global scope.

When using jsdom, however, Image is not global, but under "window.Image".

A workaround is to copy Image to the global scope in the jsdom script:
```
...
const jsdom = require('jsdom').jsdom;
global.document = jsdom('');
global.window = document.defaultView;
...
global.Image = window.Image;
```

Suggest react-konva becomes more robust by checking `Image || window.Image`

**Comment by lavrton** [comment]
@ZephD Do you want to create a pull request?

**Comment by ZephD** [comment]
Sure... First time for everything.
#61
