### ISSUE TITLE
how to set two rect with 2 zIndex?

### ISSUE THREAD

**Issue by chungchi300** [lavrton/react-konva#62]
```
      <Rect   zIndex={100} id="upper-rect"    draggable="true" x={2} y={0} width={100} height={1000} fill={'#555555'} onClick={null}/>
                      <Rect    zIndex={5}   id="lower-rect"   draggable="true"  x={20} y={20} width={50} height={50} fill={'#777777'} onClick={null}/>
```

Don't works.

**Comment by lavrton** [comment]
`zIndex` of `Konva.Node` is just current index of the node in its parent. Not like CSS property.
So you just need to place them in the correct order. `Rect` with `zIndex = 5` first then another one.

**Comment by bay007** [comment]
Hi @lavrton ; you talk about this?
`<Rect
zIndex = {5}
            name="top-right"
            x={width - size / 2}
            y={-size / 2}
            {...attributes}
          />`

**Comment by lavrton** [comment]
Ok. Looks like `zIndex` is confusing in react-konva. Looks like I should add a warning when someone trying to use it.
It is totally good to use `zIndex` in pure Konva. But it has no sense in `react-konva`, because for a correct order you just need to correctly define `render` function.

**Comment by bay007** [comment]
I want to perform like that this 
[https://konvajs.github.io/docs/groups_and_layers/Layering.html](https://konvajs.github.io/docs/groups_and_layers/Layering.html) in react, I think cant be make only defining render function.

**Comment by lavrton** [comment]
You need to have a state with an array of rectangles. Instead of setting zIndex, you just need move them in the array and then render.

**Comment by lavrton** [comment]
Using `zIndex` manually with `react-konva` is antipattern because `react-konva` will reset the order of nodes on a component update.

**Comment by bay007** [comment]
@lavrton  Thanks a lot, I going to try with your comment, I  will write my comments about this.

**Comment by bay007** [comment]
### Amazing.... that works for me...

**Comment by lavrton** [comment]
https://konvajs.org/docs/react/zIndex.html

**Comment by noumankhan95** [comment]
yes but what if i have many icons and shapes on my canvas , and im trying to move an icon over a circle shape ?
