### ISSUE TITLE
Connecting shapes

### ISSUE THREAD

**Issue by Chiranjeevi9** [lavrton/react-konva#653]
I have connected two shapes with one arrow.
when I drag and drop another shape in between two shapes it should spilt the arrow. Can you pls suggest how to do that.

**Comment by Chiranjeevi9** [comment]
Hi @lavrton  I have tried the below code
function EllipseTwo() {
  return (
    <Group 
    draggable
    >
        <Ellipse
         x={window.innerWidth/2}
         y={window.innerHeight/4}
         radiusX={40}
         radiusY= {20}
         stroke="black"
         />
         <Text
          x={window.innerWidth/2-40}
          y={window.innerHeight/4-5}
          width={80}
          height={10}
          text="Start"
          align="center"
          fontSize={15}
        />
        <ArrowPointer/>
        <Rectangle/>
        <EllipseOne/>
        </Group>

Arrow;
const ArrowPointer =()=>{
    const array =[0,0,0,110];
    return(
<Arrow
 x={window.innerWidth/2}
 y={window.innerHeight/4+20}
points={array}
stroke="black"
fill="black"
draggable
/>
    );
}

The values are static and how can I make then dynamic and, when drag and drop another shape in between ,it should create new arrow  how can I achieve that??

**Comment by lavrton** [comment]
Your question is too broad. Be more specific.

> The values are static and how can I make then dynamic

What did you try?

There are many demos/examples on draggable shapes.

> when drag and drop another shape in between ,it should create new arrow how can I achieve that

1. listen drag end
2. check its position.
3. if position is close to connecting line, update a state to have a new point in your connections

(1) and (2) is simple. Konva has API for that (3) is not related to Konva. It is just state updates.

**Comment by Chiranjeevi9** [comment]
@lavrton  My question is I have two shapes which are connected with arrow , When I place another shape in between Two shapes the arrow should split into TWO. I need your suggestions to achieve it .

**Comment by Chiranjeevi9** [comment]
@lavrton I got some Idea now thanks for the suggestion.
