### ISSUE TITLE
ReactDebugTool: debugID may not be empty

### ISSUE THREAD

**Issue by JunyuanZheng** [lavrton/react-konva#69]
I am using react-konva with golden-layout. And I get a lot of error like this:

At the begin it will throw something error like this:
![image](https://cloud.githubusercontent.com/assets/9393110/23090921/8e4cea30-f55e-11e6-8d87-84a33e3349a0.png)

and later, it is all like this.
![image](https://cloud.githubusercontent.com/assets/9393110/23090912/63e4ef4a-f55e-11e6-9ca3-4e32c367270f.png)

So I am wondering, what's the potential reason that called this problem? and how can I solve this issue?

**Comment by Weffe** [comment]
Do you mind posting the code you have using react-konva?

**Comment by JunyuanZheng** [comment]
nvm, i stop using golden layout now. thanks for the reply!
