### ISSUE TITLE
Can not add events to Stage

### ISSUE THREAD

**Issue by DMIAOCHEN** [lavrton/react-konva#7]
```javascript
<Stage ref='stage' width={width} height={height} onContentMouseDown={this.onMouseDown}>
     <Layer ref='imageLayer' />
     <Layer ref='measLayer' />
</Stage>
```

i write a demo for it:
[Demo](http://jsbin.com/wikoqefoze/1/edit?html,js,console,output)

**Comment by DMIAOCHEN** [comment]
Er...bit error with above demo, use this Instead 
[Demo](http://jsbin.com/gihemiguxa/1/edit?html,js,console,output)

**Comment by lavrton** [comment]
Fixed.
