### ISSUE TITLE
Line Component Issue

### ISSUE THREAD

**Issue by kristenakamura** [lavrton/react-konva#71]
Hi, 

I'm having trouble generating polygons properly. I tried integrating the example polygon from the Konva Doc and the rectangle konva-react demo. 

Here's what I'm seeing: http://jsbin.com/vuxatexovi/edit?js,output

Any help would be much appreciated! Thanks!

**Comment by lavrton** [comment]
@kristenakamura Hi. You should use an Array for `points` property, not a String:
```javascript
<Line
    points={[73, 70, 340, 23, 450, 60, 500, 20]}
    closed={true}
    fill={this.state.color}
    onClick={this.handleClick}
/>
```
http://jsbin.com/tinija/1/edit?js,output

**Comment by kristenakamura** [comment]
@lavrton Oh wow, my bad. Thank you so much for your help!
