### ISSUE TITLE
Layering destroyed on render

### ISSUE THREAD

**Issue by holdtb** [lavrton/react-konva#73]
Hello, I am running into issues regarding layering. Using the Konva library directly, I am able to manipulate react-konva components layering using methods such as .moveToTop() and can see it is working in browser via debugger statements. However, as soon as I re-render my component, all the layering is reset. I should also note that I have been performing the layering tweaks inside the render method of the component. I have experimented with re-ordering the creation of components as well as their ordering within a Layer/Stage to no avail. Whats the proper way to specify the z-index of a given react-konva component?

**Comment by lavrton** [comment]
You don't need to specify `zIndex` manually or with something like `moveToTop()`. Just define a correct order in you `render()` function.

**Comment by redixhumayun** [comment]
Is switching the ordering in the render function based on what order you want the layers to appear the recommended way to do it?

**Comment by lavrton** [comment]
@redixhumayun Yes, that is recommended way. It is declarative and "react-style" way. So I prefer to use it.
Otherwise, react component tree and Konva node tree may not match. So React will "reset" Konva state.
