### ISSUE TITLE
Import Stage from JSON

### ISSUE THREAD

**Issue by GosuTeacher** [lavrton/react-konva#77]
Is there any way that I can import a Stage component with children from a JSON(Like the original Konva lets you)?
Thanks.

**Comment by lavrton** [comment]
There is no way to adopt JSON serialization from `Node.toJSON()` to `react-konva`. And I think you should not do this! All you need is to serialize the state of the application (or component), and then generate Stage from from the state.

**Comment by GosuTeacher** [comment]
Thanks for clarifying this.

**Comment by kevgathuku** [comment]
Hi @lavrton how about the reverse operation i.e. exporting a React-konva Stage to an image 
e.g. through HTMLCanvasElement.toDataURL
Is that possible in `react-konva`? Thanks

**Comment by adamchenwei** [comment]
@lavrton `serialize the state of the application (or component), and then generate Stage from the state` how to do that? would you have an example available? Really appreciated!
