### ISSUE TITLE
Using local image in the image src path

### ISSUE THREAD

**Issue by bmoquist** [lavrton/react-konva#78]
I’m using the standard default configuration from create-react-app and developing locally. I’m able to run the image example using src=‘http://…yoda.jpg’ and would now like to point the image src at a local file in my project. 

I’ve tried a number of different absolute and relative file paths modifying the example but have not been able to generate the image.

Here is the folder structure of my project:

project/
---public/
------img/
---------img123.jpg
---src/
------components/
---------App.js
---index.js

Any tips on how to do this? 
Thanks so much!

**Comment by lavrton** [comment]
In CRA you have only two choices to put your assets. Inside `public` or inside `src`.
Take a look here: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-images-fonts-and-files

You can do this:
```js
import iconSrc from './relative-path/icon.png';
// later
image.src = iconSrc;
```
Or put image inside `public` and do (e.g. You have `./public/images/icon.png`):
```js
image.src = '/images/icon.png';
```

**Comment by bmoquist** [comment]
Thanks much -- both options worked perfectly! You're the best!
