### ISSUE TITLE
Improving performance for frequently changing elements

### ISSUE THREAD

**Issue by adamtal3** [lavrton/react-konva#79]
Hi,

I've been working with react-konva for a while now and I can't make it as smooth as I need it to be.

I guess my problem is that I'm re-drawing 7 complex elements (rectangles with text inside) about 300 times in a few seconds (I'm creating a timeline that moves horizontally. those are the same rectangles with a different X position).
I was wondering if it's possible to avoid re-drawing the entire element and only move it (or is it the same?).

I tried separating my timeline to different layers, some has `hitGraphEnabled={false}` if no interactions are needed.

Is there anyway I can draw 300 elements in about 4 seconds and see it render smoothly?

Thanks!

**Comment by lavrton** [comment]
@adamtal3 did you try caching? Usually, it is the best performance trick.

**Comment by adamtal3** [comment]
@lavrton - I tried adding caching but I can't spot any difference, still the same glitches.

I'll try to isolate the problem. There might be something else that affects the performance.

Thanks for your fast response.
