### ISSUE TITLE
Nesting user components and react-konva components

### ISSUE THREAD

**Issue by rhoegg** [lavrton/react-konva#8]
I would like to create my own components that render using react-konva, and also have a parent child relationship.  For example:

```javascript
class Frame extends React.Component {
    render() {
        return ( 
            <Layer x={10} y={10}>
                <Rect width={50} height={30} stroke={'black'} />
                <Artwork />
            </Layer>
        )
    }
}

class Artwork extends React.Component {
    render() {
        return ( <Rect x={5} y={5} width={40} height={20} fill={'red'} /> )
    }
}
```

This seems to mostly work, except the child konva components don't seem to be connected to their parent konva components. This causes relative position, scale, rotation, etc. to be lost.

**Comment by lavrton** [comment]
@rhoegg please provide example. This works fine: http://jsbin.com/nivefi/2/edit?js,output

**Comment by rhoegg** [comment]
You're right, an unrelated problem was causing my inner components to render incorrectly.
