### ISSUE TITLE
Deprecation warnings in React 15.5

### ISSUE THREAD

**Issue by samelliottdlt** [lavrton/react-konva#85]
React 15.5 will now issue deprecation warnings on using createClass and proptypes. These are now available as standalone packages here:

https://www.npmjs.com/package/prop-types
https://www.npmjs.com/package/create-react-class

More details from the React blog: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

The upgrade looks to be really straightforward, I can make a pull request for this if that would be preferable :)

**Comment by lavrton** [comment]
@samelliottdlt you can make pull request.
