### ISSUE TITLE
Example for using Sprite

### ISSUE THREAD

**Issue by prark** [lavrton/react-konva#88]
I am trying 

```
             <Sprite image={imageObj} x={300} y={300} 
                animations={
                    {
                    standing:[
                      0,0,64,64,
                        192,0,64,64            
                      ]
                }}
                animation={'standing'}
                frameRate={2}
                frameIndex={0}
                >
                </Sprite>

```

and it renders the first frame, however it doesn't start the animation. How do you trigger .start() on the underlying sprite instance?

**Comment by lavrton** [comment]
Right now you have to manually start it by accessing direct Konva object with `ref` property. And then in `componentDidMount` do something like this:
```javascript
componentDidMount() {
  this.spriteNode.start();
}
```

I guess it will be better if `react-konva` can handle this case automatically.

**Comment by prark** [comment]
Thank you. I used `ref={(node => {node.start()})}` and it works.

**Comment by prark** [comment]
Changing to `ref={(node => {if(node && !node.isRunning()) node.start()})}` prevents calling start repeatedly.
