### ISSUE TITLE
How to use Label?

### ISSUE THREAD

**Issue by SudoGetBeer** [lavrton/react-konva#97]
Hey,

i cant get the example ( https://konvajs.github.io/docs/shapes/Label.html ) for labels running.

My Try: http://jsbin.com/puvazabota/edit?html,js,output

Maybe somebody knows the solution.

**Comment by lavrton** [comment]
Hi. Currently, `react-konva` do not make automatic type conversion.
So instead of:
```
<Tag pointerWidth="10" />
```
You need to write:
```
<Tag pointerWidth={10} />
```
Otherwise the math will be broken.
See: http://jsbin.com/yusoficera/1/edit?js,output

**Comment by SudoGetBeer** [comment]
Ah, thank you!
