### ISSUE TITLE
Support with Meteor 

### ISSUE THREAD

**Issue by lur9622** [lavrton/react-konva#98]
Hello, there is no support for meteor since Jan 2015. (Last commit jsdom). Is It possibile to do some thing ?

**Comment by janus-reith** [comment]
I am currently using it in Meteor 1.5. It works, but I get a server warning in startup, that an npm module canvas is missing

**Comment by lavrton** [comment]
I removed all NodeJS deps from `Konva` core. Probably the issue is fixed.
Add more info if you still have issues.
